name: Build AppImage and release if on main

on:
  push:
  pull_request:

env:
  DEBIAN_FRONTEND: noninteractive

permissions:
  contents: write

jobs:
  build:
    # old distro = old glibc = AppImage will run on most Linux PC's
    runs-on: ubuntu-24.04
    outputs:
      ARTFNAME: ${{ steps.hash.outputs.ARTFNAME }}
    steps:
    - name: Install tools and depedencies
      run: |
        sudo apt-get update
        sudo apt-get install meson libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev nlohmann-json3-dev
    - name: Check out
      uses: actions/checkout@v7
    - name: Set up Meson
      run: |
        mkdir builddir
        meson setup builddir
        meson configure -Dprefix=/usr builddir
    - name: Build
      run: meson install -C builddir --destdir ../AppDir
    - name: Download AppImage tools
      run: |
        wget https://github.com/linuxdeploy/linuxdeploy/releases/latest/download/linuxdeploy-x86_64.AppImage
        chmod +x linuxdeploy-x86_64.AppImage
        wget https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/latest/download/linuxdeploy-plugin-appimage-x86_64.AppImage
        chmod +x linuxdeploy-plugin-appimage-x86_64.AppImage
    - name: Build AppImage
      run: ./linuxdeploy-x86_64.AppImage --appdir AppDir --output appimage
    - name: Add commit hash to artifact name
      id: hash
      run: |
        SHA_SHORT=$(git rev-parse --short=8 HEAD)
        ARTFNAME=Drunken_Walk-$SHA_SHORT-x86_64.AppImage
        echo "ARTFNAME=$ARTFNAME" | tee -a $GITHUB_ENV $GITHUB_OUTPUT
        mv Drunken_Walk-x86_64.AppImage $ARTFNAME
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        path: ${{ env.ARTFNAME }}
        archive: "false"
        if-no-files-found: error
  release:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - name: Download build output
      uses: actions/download-artifact@v8
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ARTFNAME: ${{ needs.build.outputs.ARTFNAME }}
        REPO: ${{ github.repository }}
      run: |
        wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
        chmod +x pyuploadtool-x86_64.AppImage
        GH_TOKEN="$GITHUB_TOKEN"
        gh release delete continuous --cleanup-tag --yes -R "$REPO"
        ./pyuploadtool-x86_64.AppImage "$ARTFNAME"
